const deck = [
    { suit: 'clubs', value: 2, imageURL: '2_of_clubs.png'},
    { suit: 'clubs', value: 3, imageURL:  '3_of_clubs.png'},
    { suit: 'clubs', value: 4, imageURL:  '4_of_clubs.png'},
    { suit: 'clubs', value: 5, imageURL:  '5_of_clubs.png'},
    { suit: 'clubs', value: 6, imageURL:  '6_of_clubs.png'},
    { suit: 'clubs', value: 7, imageURL: '7_of_clubs.png' },
    { suit: 'clubs', value: 8, imageURL: '8_of_clubs.png' },
    { suit: 'clubs', value: 9, imageURL:  '9_of_clubs.png'},
    { suit: 'clubs', value: 10, imageURL: '10_of_clubs.png' },
    { suit: 'clubs', value: 11, imageURL: 'jack_of_clubs.png' },
    { suit: 'clubs', value: 12, imageURL: 'queen_of_clubs.png' },
    { suit: 'clubs', value: 13, imageURL: 'king_of_clubs.png' },
    { suit: 'clubs', value: 14, imageURL: 'ace_of_clubs.png' },
    { suit: 'diamonds', value: 2, imageURL:  '2_of_diamonds.png'},
    { suit: 'diamonds', value: 3, imageURL:  '3_of_diamonds.png'},
    { suit: 'diamonds', value: 4, imageURL:  '4_of_diamonds.png'},
    { suit: 'diamonds', value: 5, imageURL:  '5_of_diamonds.png'},
    { suit: 'diamonds', value: 6, imageURL:  '6_of_diamonds.png'},
    { suit: 'diamonds', value: 7, imageURL:  '7_of_diamonds.png'},
    { suit: 'diamonds', value: 8, imageURL:  '8_of_diamonds.png'},
    { suit: 'diamonds', value: 9, imageURL:  '9_of_diamonds.png'},
    { suit: 'diamonds', value: 10, imageURL:  '10_of_diamonds.png'},
    { suit: 'diamonds', value: 11, imageURL:  'jack_of_diamonds.png'},
    { suit: 'diamonds', value: 12 , imageURL: 'queen_of_diamonds.png'},
    { suit: 'diamonds', value: 13, imageURL:  'king_of_diamonds.png'},
    { suit: 'diamonds', value: 14, imageURL:  'ace_of_diamonds.png'},
    { suit: 'hearts', value: 2, imageURL: '2_of_hearts.png' },
    { suit: 'hearts', value: 3, imageURL:'3_of_hearts.png' },
    { suit: 'hearts', value: 4, imageURL:  '4_of_hearts.png'},
    { suit: 'hearts', value: 5, imageURL:  '5_of_hearts.png'},
    { suit: 'hearts', value: 6, imageURL:  '6_of_hearts.png'},
    { suit: 'hearts', value: 7, imageURL:  '7_of_hearts.png'},
    { suit: 'hearts', value: 8 , imageURL: '8_of_hearts.png'},
    { suit: 'hearts', value: 9, imageURL:  '9_of_hearts.png'},
    { suit: 'hearts', value: 10, imageURL:  '10_of_hearts.png'},
    { suit: 'hearts', value: 11, imageURL:  'jack_of_hearts.png'},
    { suit: 'hearts', value: 12 , imageURL: 'queen_of_hearts.png'},
    { suit: 'hearts', value: 13 , imageURL: 'king_of_hearts.png'},
    { suit: 'hearts', value: 14 , imageURL: 'ace_of_hearts.png'},
    { suit: 'spades', value: 2, imageURL:  '2_of_spades.png'},
    { suit: 'spades', value: 3, imageURL: '3_of_spades.png'},
    { suit: 'spades', value: 4, imageURL:  '4_of_spades.png'},
    { suit: 'spades', value: 5, imageURL:  '5_of_spades.png'},
    { suit: 'spades', value: 6, imageURL:  '6_of_spades.png'},
    { suit: 'spades', value: 7, imageURL:  '7_of_spades.png'},
    { suit: 'spades', value: 8, imageURL:  '8_of_spades.png'},
    { suit: 'spades', value: 9, imageURL:  '9_of_spades.png'},
    { suit: 'spades', value: 10, imageURL:  '10_of_spades.png'},
    { suit: 'spades', value: 11, imageURL:  'jack_of_spades.png'},
    { suit: 'spades', value: 12, imageURL:  'queen_of_spades.png'},
    { suit: 'spades', value: 13, imageURL:  'king_of_spades.png'},
    { suit: 'spades', value: 14, imageURL: 'ace_of_spades.png' }
]

module.exports = {
    deck
};
